config/routes.rb
Rails.application.routes.draw do

  resources :topics do
    resources :posts, except: [:index]
  end
  
  devise_for :users
  root to: 'welcome#index'

  get 'welcome/pharmacy'

  get 'welcome/blog'

  get 'welcome/about'

  get 'welcome/contact'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :body, length: { minimum: 5 }, presence: true
  validates :user, presence: true
  default_scope { order('updated_at ASC') }
  
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user
  has_many :comments, dependent: :destroy
  

  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true
  validates :topic, presence: true
  validates :user, presence: true
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  validates :name, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 15 }, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [ :index, :show ]
  before_filter :configure_permitted_parameters, if: :devise_controller?

  before_filter :configure_permitted_parameters,
                if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
   @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
   @post = current_user.posts.build(post_params)
   @topic = Topic.find(params[:topic_id])

   @post.topic = @topic

   if @post.save!
     flash[:notice] = "Post was saved."
     redirect_to [@topic, @post]
   else
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :new
   end
  end

  def update
    @post = current_user.posts.build(post_params)
    @topic = Topic.find(params[:topic_id])
    @post.assign_attributes(post_params)

    @post.topic = @topic

   if @post.save!
     flash[:notice] = "Post was updated."
     redirect_to [@topic, @post]
   else
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :edit
   end
  end

   def destroy
     @post = Post.find(params[:id])

     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.topic
     else
       flash.now[:alert] = "There was an error deleting the post."
       render :show
     end
   end

   private

   def post_params
     params.require(:post).permit(:title, :body, :image_url)
   end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
   @topic = Topic.find(params[:id])
  end

   def new
     @topic = Topic.new
   end

   def edit
     @topic = Topic.find(params[:id])
   end

   def create
     @topic = Topic.new(topic_params)

     if @topic.save
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash.now[:alert] = "Error creating topic. Please try again."
       render :new
     end
   end

   def update
     @topic = Topic.find(params[:id])
     @topic.assign_attributes(topic_params)
     

     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash.now[:alert] = "Error saving topic. Please try again."
       render :edit
     end
   end

   def destroy
     @topic = Topic.find(params[:id])

     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash.now[:alert] = "There was an error deleting the topic."
       render :show
     end
   end

   private

   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def pharmacy
  end

  def blog
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<div class="container">
<nav class="navbar navbar-tabs">
<div class="container-fluid">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse" id="myNavbar">
    <ul class="nav navbar-nav">
      <li class="active"><%= link_to "Home", root_path %></li>
      <li class="dropdown">
        <li><a class="dropdown-toggle" data-toggle="dropdown" href="<%= welcome_about_path %>">Pharmacy</a></li>
          <ul class="dropdown-menu">
          <li><a href="#">Page 1-1</a></li>
          <li><a href="#">Page 1-2</a></li>
          <li><a href="#">Page 1-3</a></li>
        </ul>
      </li>
      <li><%= link_to "Blog", welcome_about_path %></li>
      <li><%= link_to "About", welcome_about_path %></li>
      <li><%= link_to "Contact", welcome_about_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
      <li class="dropdown">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
          Hello <span class="glyphicon glyphicon-user"></span> <%= current_user.name %>
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Profile', edit_user_registration_path %></li>
          <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
        </ul>
      </li>
    <% else %>
      <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
      <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    <% end %>

    </ul>
  </div>
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Independent Pharmacy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<header>
  <div class="container">
  <nav class="navbar navbar-tabs">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "Home", root_path %></li>
        <li class="dropdown">
          <li><a class="dropdown-toggle" data-toggle="dropdown" href="<%= welcome_about_path %>">Pharmacy</a></li>
            <ul class="dropdown-menu">
            <li><a href="#">Page 1-1</a></li>
            <li><a href="#">Page 1-2</a></li>
            <li><a href="#">Page 1-3</a></li>
          </ul>
        </li>
        <li><%= link_to "Blog", topics_path %></li>
        <li><%= link_to "About", welcome_about_path %></li>
        <li><%= link_to "Contact", welcome_about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            Hello <span class="glyphicon glyphicon-user"></span> <%= current_user.name %>
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Profile', edit_user_registration_path %></li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <li><a href="<%= new_user_registration_path %>"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="<%= new_user_session_path %>"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      <% end %>

      </ul>
    </div>
  </div>
  </nav>


  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
  <% end %>
  </div>
</header>

<body>
    <%= yield %>


</body>
</html>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Edit Post</h1>

  <div class="row">

   <div class="col-md-8">
     <%= form_for [@post.topic, @post] do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>

       <div class="form-group">
         <%= f.label :image_url %>
         <%= f.text_field :image_url, class: 'form-control', placeholder: "Enter post image" %>
       </div>


       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= image_tag('generalhealth2.jpg') %>
   </div>
  </div>
  </div>

app/views/posts/index.html.erb
<div class="container">
  <h1>All Posts</h1>


  <% @posts.each do |post| %>
   <div class="media">
     <div class="media-body">
       <h4 class="media-heading">

         <%= link_to post.title, post %>
       </h4>
     </div>
   </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>

   <div class="row">
       <div class="col-md-4">
         <%= image_tag('search2.jpg') %>
       </div>
       <div class="col-md-8">
         <%= form_for [@topic, @post] do |f| %>
           <div class="form-group">
             <%= f.label :title %>
             <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
           </div>
           <div class="form-group">
             <%= f.label :body %>
             <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
           </div>
           <div class="form-group">
             <%= f.label :image_url %>
             <%= f.text_field :image_url, class: 'form-control', placeholder: "Enter post image" %>
           </div>


           <div class="form-group">
             <%= f.submit "Save", class: 'btn btn-success' %>
           </div>
         <% end %>
       </div>
   </div>
 </div>

app/views/posts/show.html.erb
<div class='container'>
  <h1><%= @post.title %></h1>

 <div class="row">
   <div class="col-md-8">
     <p><%= @post.body %></p>
     <p><%= image_tag(@post.image_url, size: "200x200")%>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
     <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
   </div>
 </div>
</div>

app/views/topics/edit.html.erb
<div class="container">
  <div id="Topics"></div>
</div>

<!-- <h1>Edit Topic</h1>

 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">

         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div> -->

app/views/topics/index.html.erb
<div class="container">
  <h1>Topics</h1>
  <div>
    <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
  </div><br />
     <div class="row">
       <div class="col-md-8">
         <% @topics.each do |topic| %>
           <div class="media">
             <div class="media-body">
               <h4 class="media-heading">
                 <%= link_to topic.name, topic %>
               </h4>
               <small>
                 <%= topic.description %>
               </small>
             </div>
           </div>
         <% end %>
       </div>
    </div>
  </div>
</div>

app/views/topics/new.html.erb
<div class="container">
  <h1>New Topic</h1>

  <div class="row">
   <div class="col-md-4">
     <%= image_tag('pestle1.jpg') %>
   </div>
   <div class="col-md-8">
     <%= form_for @topic do |f| %>
       <div class="form-group">
         <%= f.label :name %>
         <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= f.label :description %>
         <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
       </div>
       <div class="form-group">
         <%= f.label :public, class: 'checkbox' do %>
           <%= f.check_box :public %> Public topic
         <% end %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="container">
  <h1><%= @topic.name %></h1>

   <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
   <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>

   <div class="row">
     <div class="col-md-8">
       <p class="lead"><%= @topic.description %></p>
       <% @topic.posts.each do |post| %>
         <div class="media">
           <div class="media-body">
             <h4 class="media-heading">
               <%= link_to post.title, topic_post_path(@topic, post) %>
             </h4>
             <small>
               submitted <%= time_ago_in_words(post.created_at) %> ago <br>
               <%= post.comments.count %> Comments
             </small>
           </div>
         </div>
       <% end %>
     </div>
     <div class="col-md-4">
       <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     </div>
   </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/blog.html.erb
<h1>Welcome#blog</h1>
<p>Find me in app/views/welcome/blog.html.erb</p>

app/views/welcome/contact.html.erb
<h1>Welcome#contact</h1>
<p>Find me in app/views/welcome/contact.html.erb</p>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Independent Pharmacy</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <div class="image1">

    </div>
  </div>
</body>
</html>

app/views/welcome/pharmacy.html.erb
<h1>Welcome#pharmacy</h1>
<p>Find me in app/views/welcome/pharmacy.html.erb</p>